// SPDX-License-Identifier: Apache-2.0
:doctype: article

== Go Port

This file describes the Go port of micro.

=== Source code location

The Go code is stored at the top level project directory. This means the code is stored online at github.com/bantling/micro,
which means import statements in go can import any package as `import github.com/bantling/micro/<package>`.

=== Packages

* app
** Help write a data-driven application using a TOML file
** Consider using SQLPage to generate the html: see https://sql.ophir.dev
* constraint
** defines generic type constraints, some are similar to golang.org/x/exp/constraints
* conv
** converts between numeric types, returning an error if any loss of precision would occur
* encoding/json
** Value type that describes any kind of JSON value
** convert between go types to Value and vice-versa (eg, map[string]any -> Value of type Object -> map[string]any)
** default numeric type is NumberString, but custom conversion functions can be used for some other numeric type
** streaming parser that can provide individual elements of top level array as they are read in, so that a large number
of elements can be processed without having to read entire input.
** write a json.Value to a writer
* event
** A simple system for sending events and getting results back
** Same generic type is used for input and output
** default registry can be used to send and receive json.Value objects
* funcs
** slices:
*** flatten multiple dimensions into one
*** access elements safely
*** remove elements
*** reverse elements
*** sort elements
** maps:
*** access keys safely
*** sort key/value pairs
** filters - func(T) bool:
*** compose with and, or, not
*** generate filters for comparisons (<, <=, ==, >=, >)
*** generate filters for is negative, is non-negative, is positive, is nil, is non nil
** compose any number of funcs that accept and receive same type
** compose 2 to 10 funcs that accept and return different types
** ternary - take a (bool, true value, false value) or (bool, true supplier, false supplier), and return true or false value
** min/max
** nil handling
** error handling
** supplier generators
** generate a func that ignores result of another func
** TryTo is a replacement for awkward idiomatic go code that acts like a Java try/catch/finally block:
   Accepts a func for a try block, a func for a catch block (only invoked if try block panics), and any number of
   closer funcs that close resources regardless of whether the try func panics.
* io
** ErrorReader and ErrorWriter returns a specified error after reading or writing a specified set of bytes, mostly useful
   for unit tests.
** writer package is reverse of Iter, writes values to a destination rather than reading. Mostly concerned with writing to IO.
* iter
** defines Iter type that can iterate anything
** based on iterating funcs, a func of no args that returns (value, bool), where the value is only relevant if the bool
   is true
** A number of constructors are provided for hard-coded values, slices, maps, io.Reader, concat multiple iters
** Next method returns (T, error)
** Unread method builds a buffer that is read in reverse order (eg Unread(1) followed by Unread(2) provides values 2, 1)
** Maybe func accepts an Iter and returns a Result, which provides either a value or an error
** SetError func accepts an Iter and an error, and returns a new Iter that returns the given error after exhausting the Iter.
   Mostly useful for unit tests.
* math
** absolute value calculation that returns an error for lowest negative value of integers
   (eg for int8, abs(-128) = -128 because highest positive value is 127)
** add/subtract/multiply integers and return an error if over/underflow occurs
** integer division that rounds quotient up when remainder >= half way point
** generate a mask of n consecutive 1 bits that are left or right aligned
** min and mask functions for all numeric types
* reflect
** utilities to make reflection usage easier
** DerefType derefs a Type until it is not a pointer
** DerefTypeMaxOnePtr derefs a Type until it is zero or one pointers (eg, two or more pointers get derefd to one pointer)
** DerefValue derefs a Value until it is not a pointer. If any pointer is nil, an invalid Value is returned.
** DerefValueMaxOnePtr derefs a Value until it is zero or one pointers (eg, two or more pointers get derefd to one pointer)
   If any pointer except the last one is nil, an invalid Value is returned.
** FieldsByName collects the fields of a struct into a map
** IsBigPtr returns true if the given type is a *big.Int, *big.Float, or *big.Rat, and false otherwise
** IsNillable returns true if a Value or Type represents a type that can be assigned nil
** IsPrimitive returns true if a Value or Type represents a primitive value
** ResolveValueType resolves the type of a Value so it is not interface{} (eg, an interface{} that is really an int resolves to int).
   If the Value is already not interface{}, it is returned as is.
** ToBaseType converts zero or one pointers to a primitive subtype to the underlying type (eg rune -> int32, or *rune to *int32)
** ValueMaxOnePtrType returns the underlying Type of zero or one pointers to a Value.
   If the Value given has multiple pointers, the Value is not a valid parameter value, and the result is nil.
* stream
** Provides streaming functionality (similar to that of Java 8 streams).
** Some functions take params and return a func of Iter[T] -> Iter[U]
** Remaining functions are a func of Iter[T] -> Iter[U]
** All functions are a transform
** Funcs that result in zero or one elements return an Iter instead of a Result, to allow continued usage of other
   funcs that accept and return iters.
* tuple
** Tuples of 2, 3, or 4 elements of one generic type or separate generic types
* union
** Unions of 2, 3 or 4 elements of separate generic types
** Result is union of one generic type and an error
* util
** Range can hold a range of values between a minimum and maximum, where minimum and maximum values themselves may or
   may not be allowed. Attempting to set the value outside the range returns an error and does not change the value.

=== Dependency Graph

A dependency graph can be generated anytime by running `make depgraph`, which produces several files:

[cols="1,1"]
|===
|File
|Purpose

|link:depgraph.svg[]
|A complete dependency graph

|link:depgraph.above.svg[]
|A graph of iter package and above

|link:depgraph.below.svg[]
|A graph of iter package and below
|===

=== Makefile

[cols="1,1,1"]
|===
|Target
|Purpose
|Options

|all (default)
|builds on host
|

|docker
|builds in a docker container such that every build has to download dependencies and build from scratch
|

|docker-cache
|builds in a docker container with caching for dependencies and compiling across builds
|

|podman
|builds in a podman container such that every build has to download dependencies and build from scratch
|

|podman-cache
|builds in a podman container with caching for dependencies and compiling across builds
|

|tidy
|runs `go mod tidy`, and cleanup tasks for docker-cache or podman-cache
|

|compile
|runs `go build ./...`, and cleanup tasks for docker-cache or podman-cache
|

|lint
|runs `go vet ./...`
|

|format
|runs `gofmt -s -w` in every go package dir to format source code
|

|test
|runs `go test ./...` in every go package dir to test source code
|`-count=num` to run tests N times, `pkg=./package_name` to test only one package, `run=test_name` to run matching tests

|coverage
|runs `go tool cover` to display code coverage in default browser
|

|have-dot
|Check if graphViz `dot` program is installed, fail with an error message if not
|

|depgraph
|Creates the three dependency graph files described above using graphViz dot program
|

|have-asciidoc
|Check if `asciidoc` program is installed, fail with an error message if not
|

|.readme.html
| Generates an HTML version of top level README.adoc using asciidoc, output should be the same as GitHub or GitLab
|

|.readme.go.html
| Generates an HTML version of this README using asciidoc, output should be the same as GitHub or GitLab
|

|vars
| Displays all variables declared in the Makefile, useful for debugging issues with docker or podman targets
|

|clean
| Removes docker and podman caches from host
|
|===

=== TODO

* Rename util package to range, funcs is really a util package
* Reference app
** Every file in this app is something that can be produced by code generator
** DDL scripts
** Persistence
** REST code
** Server side HTML templates
* Code generation
** Define data types
** Unions with a discriminator enum (eg animal that is union of bird, fish, or dog, and enum specifies which one)
** Self-referencing types (eg animal contains animal)
** required fields
** user defined fields stored in a map[string]any
** allow int8/16/32/64,uint8/16/32/64 (not int or uint as they vary in size), string, float (32), double (64)
** date in iso 8601
*** date as YYYY-MM-DD
*** month as YYYY-MM
*** time as THH:MM:SS, or THH:MM:SS.SSS
*** duration/intervals as PnYnMnDTnHnMnS, nY years, nM months, etc (days, hours, minutes, seconds)
*** smallest specified part in duration may have a fraction (eg P0.5Y or P0,5Y both mean half a year)
** other defined structs
** arrays of a specific type (eg array of string, array of animal, etc)
** maps of a specific key and value type (eg map of string to int)
** no any type or generics
** generate structs using text/template
* ETL
** Mainly operating on streams, with 3 basic operation types:
*** Combine streams
*** Split streams
*** Generate streams
** Look at steps Pentaho and Talend provide as a rough guide
* Consider porting https://github.com/dnotq/decNumber to Go for arbitrary precision decimal math
