// SPDX-License-Identifier: Apache-2.0
:doctype:article

= Micro

Micro is a small library of useful stuff for small projects, particularly (but not limited to) REST/database projects.

== Packages

* constraint
** defines generic type constraints, some are similar to golang.org/x/exp/constraints
* conv
** converts between numeric types, panicking if any loss of precision would occur
* funcs
** slices:
*** access elements safely
*** flatten multiple dimensions into one
*** reverse elements
*** sort elements
** maps: access keys safely
** filter - func(T) bool:
*** compose with and, or, not
*** generate filters for comparisons (<, <=, ==, >=, >)
*** generate filters for is negative, is non-negative, is positive, is nil, is non nil
** compose any number of funcs that accept and receive same type
** compose up to 10 funcs that accept and return different types
** ternary - take a bool, true value or supplier, false value or supplier, and return true or false value
** min/max
** nil handling
** supplier generators
** generate a func that ignores result of another func
** TryTo is a replacement for hard to write idiomatic go code that acts like a Java try/catch/finally block:
   Accepts a func for a try block, a func for a catch block (only invoked if try block panics), and any number of
   closer funcs that close resources regardless of whether the try func panics.
* iter
** defines Iter type that can iterate anything
** based on iterating funcs, a func of no args that returns (value, bool), where the value is only relevant if the bool
   is true
** A number of constructors are provided for hard-coded values, slices, maps, io.reader, concat multiple iters
** Next, value, unread, and Must funcs to retrieve values
** Provides streaming functionality (similar to that of Java 8 streams).
    Most functions accept ands return an Iter, providing some kind of transform.
*** funcs for first, map, filter, reduce, expand, skip, limit, peek, generate infinite series, all match, any match,
   none match, count, distinct, duplicate, reverse, sort, and parallel
*** control over how and when parallel execution occurs, default algorithm provided
* json
** Value type that describes any kind of JSON value
** Convert between go types to Value and vice-versa (eg, map[string]any -> Value of type Object -> map[string]any)
** default numeric type is NumberString, but custom conversion functions can be used for some other numeric type
* util
** Provides ErrorReader to return a specified error after reading a specified set of bytes; useful for unit tests.

== TODO

* Modify tests to test errors/panics with strings rather than calling fmt to generate, to ensure string is readable.
* Auto convert each JSON object into Go structs and vice-versa
* Auto write JSON objects to an SQL table that holds a JSON column
* Auto write JSON objects to an SQL table that uses individual columns for each field
* Consider providing simplistic string based arbitrary concurrency that is not fast, but just does basic operations
